language: java
jdk: openjdk11
os: linux
dist: xenial
cache:
  timeout: 180
  directories:
  - "$HOME/.m2/repository"
install:
- ./scripts/install.sh
script:
- ./scripts/build.sh
before_cache:
- rm -rf $HOME/.m2/repository/org/opencds/cqf/cql/evaluator*
notifications:
  slack:
    - rooms:
      - secure: NS0wLbgDgtmShBFpSYzi67ef/6lhFBiCw9nkJCHT+a47FXQb1l+dUk4EAd9SjpWHBO1YcL5yZ95+QaweVhKyEjAxlxJVNpAh3Yg9zskjrzfGqK5Uwz+HhcctyuzJ+GVhn4Ri+1NSqKp4uL2UvmqtrTCdwZ8r7z6s8Q7Q+Mh+JdTNpujCT3iziOL2zK20fay5kS/DX3CiA8wUKYxqWxLMlhv+L9/ZyFztuVWYJO1+J1tC27twlzVAwL/tP38m/X7WB7ITp9koWX+8+2R7mgTnCGNJrSMZH4+iNCnmcRr5m5LGbvaaK59JnhylkAN5X3+ojMN450AA1nHL+hEYfxhARoy4wQ6u9g/3qkbRSXFvCjWvSUJnVAkCNAGPR68Q415mkdnS9UJ1PdRa0HPGjuxGv3CIWmJzAuXo2TNj9NakVKyOh/TZh8OrYQifhF4sLx9DTntHaxJtfB/SWZ9Vvj92YPRC6l3YCtLrFdxisEIa4N+EYxZXiTE1bCUpoCld7h7U5q1vmBKafv8z0HhCFrR5QSXPDby3fuU7oIKX3drn3HVnyBrbkQFapYXOKHD/O71DHitgFYSMp3zpRar2niMiQm6AJVry1oAxlo/x99UiZrFRrU+PuSLT9vzasfTf88HuYihcfDBF0HMOUmXRVR/ORdqS8AHn0r/9FprqDDTRK9Q=
      on_success: always
      on_failure: never
    - rooms:
      - secure: P6dxCL+vydKFJmpS0K3GeXHjL5Gyy75qCfLa1kEa/bzerDOOsjL/g0XcsKE0YNsmJlPGTHXxRbYJWEf2eZAFYZll38Se26j4IwqP4oeO5VKUhVYNfQYkgC2pu4y5F10sjcJxq4krSvnYGiEZNxgIKxu9ZOz1/kVQCRRA8ixJo1AutFTMvYvoRGPA5K6QPkqhyqsK2dOQnxhxKdq+oAgxOOPeB43zWlGTFtIqhySnF0xGT3Im25+J4GlV0++TcIwDxV7k05krSPKeoo9mvsMLv5KXU5MkFRvSSCST0ag9rBDUJuP2Gy1CCt/xmu4B3mLAF1Np7LVhGJGiH6BCbkI+CKogXjYJg4DIkzxXquthstzq3Z9JHVcZ94Y1TrpWmgPhVNtUfSISPLMD/8lBI/Gr3gXTdFGMJr5vVo/ch04dvyklVnzx49RbvSJ8FLX0QmqfCIyP7NLS9B/ooXas9L/Ufo6Z9qd6f2QRJGY4rJYQ+nQ1wjJP7bHYEbf/hbfU2YHs8ChJM/zu/JdNSw/a7KhtLVj29z/IsAVEsYlEvagrI3TfPGXyz6YGeoGWuUjGjTZOVXy+D1VrH6dNqnXcTWXeySHrc7vDEO+GCT69xHhoxAUDtP/qFdfjRgaXGVAjZpvCgUkT5tfc8cIfEV35vfHcgsC41ggVgHxXhV/50pDj4sY=
      on_success: never
      on_failure: always